application: yourusername-movie-quotes # TODO: Fix username
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# TODO: Add builtin for deferred library to make a Task Queue

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

# Serving static files (css, images, etc)
- url: /static
  static_dir: static

# Data import
# TODO: Protect the /importdata path so only admin users can run the data import.

# TODO: Add special case /quiz.html handler
    
# Use the get and post handlers for everything else
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

